### ISSUE TITLE
Contao 4 Support

### ISSUE THREAD

**Issue by iCodr8** [hschottm/calendar_ical#10]
Wird diese Erweiterung noch so angepasst, dass sie auf Contao 4 genutzt werden kann?

**Comment by iCodr8** [comment]
Ich habe es mal geforked und baue es soweit wie möglich auf Contao 4 um. Wenn ich damit fertig bin können wir gerne einen Pull Request daraus machen.

https://github.com/Craffft/contao-calendar-ical-bundle

**Comment by Jaaaan** [comment]
Den Vorschlag befürworte ich.
Ist es denn auch geplant, das Bundle über den Contao Manager verfügbar zu machen?

**Comment by iCodr8** [comment]
Ich habe keine Ahnung, was für den Contao Manager angepasst werden muss. Ich bin ehrlich gesagt kein Freund davon und habe auch nicht vor diesen zu nutzen. Wenn es jetzt zwei Zeilen Code sind die angepasst werden müssen, dann baue ich das für euch ein. Wenn es jedoch erheblichen Mehraufwand bedeutet, dann würde ich um einen Pull-Request bitten.

**Comment by Jaaaan** [comment]
Um sie für den Contao Manager verfügbar zu machen, muss sie auch im Composer Client verfügbar sein. D. h., dass die Erweiterung auf Packagist verfügbar ist: https://packagist.org/

Man kann die Erweiterung weiterhin als Contao Bundle zur Verfügung stellen, so wäre sie auch für den Composer Client unter Contao 3 verfügbar: https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md

**Comment by Jaaaan** [comment]
Ich sehe gerade, dass Du bereits Erweiterungen für Contao 4 erstellt hast. Diese sind auch im CM zu finden und lassen sich erfolgreich installieren.
Es wäre also das gleiche Vorgehen wie bei deinen bisherigen Erweiterungen.

**Comment by iCodr8** [comment]
Dann muss man dafür wohl nichts machen :)

**Comment by iCodr8** [comment]
@hschottm: Ich habe nun alles auf Contao 4 umgebaut. Die Lizenz ist weiterhin LGPL, aber ich habe das in ein LICENCE file ausgelagert. Mein Fork ist via Packagist verfügbar.
https://packagist.org/packages/craffft/contao-calendar-ical-bundle

**Comment by Jaaaan** [comment]
Danke schonmal!

Noch findet der CM nichts, könnte daran liegen, dass der CM aktuell nur Pakete vom Typ `contao-bundle` bzw. `contao-module` unterstützt.

**Comment by iCodr8** [comment]
Ja, hab es jetzt bei der iCal Erweiterung und allen meinen bereits auf Contao 4 portierten Erweiterungen auf contao-bundle gestellt. Es funktioniert :)
Und man muss ehrlich sagen der Contao Manager ist echt hübsch geworden. Aber verwenden werde ich ihn wahrscheinlich trotzdem nicht.

![ical-cm](https://user-images.githubusercontent.com/1264033/27773173-18cc7020-5f74-11e7-9021-d40967be879b.png)

**Comment by Jaaaan** [comment]
Vielen Dank nochmals!! 
Ja, als grafische Oberfläche eignet er sich besonders, wenn man keinen SSH-Zugriff hat. ;-)

Leider ist mir noch etwas aufgefallen:
![calendar_inkompatibel](https://user-images.githubusercontent.com/16544159/27773271-35fb3602-5f76-11e7-82d9-90206e27b6b4.PNG)

**Comment by Jaaaan** [comment]
Das sollte helfen, damit der CM die Erweiterung aktivieren kann:
```
	"require-dev": {
		"contao/manager-plugin": "^2.0"
},
```
