### ISSUE TITLE
Fehler beim Import von iCal-Dateien mit mehrzeiligem Feld X-WR-CALDESC

### ISSUE THREAD

**Issue by janfux** [hschottm/calendar_ical#5]
Hallo,
beim Import einer iCal Datei aus einem Google Kalender trat folgender Fehler auf: Der Import lief immer bis zum Abbruch durch Überschreitung der Skriptlaufzeit, wobei keine neuen Einträge in der tl_calendar_events angelegt wurden. Durch den Skriptabbruch leider keine Fehlermeldung.

Das Verhalten konnte auch mit einer Teilmenge der betreffenden Datei reproduziert werden, solange der Kopf der Datei unverändert blieb.

Die einzige auffällige Unregelmäßigkeit war ein zweizeiliges X-WR-CALDESC: Feld im Kopf der Datei, wo Google eine längere Beschreibung einfach auf die nächste Zeile umgebrochen hat, allerdings in der zweiten Zeile eingeleitet durch ein Leerzeichen.

Nach Entfernen der zweiten Zeile verlief der Import der aus Google Cal exportierten Datei fehlerfrei. Nach Änderung des Kommentars im betreffenden Google Kalender klappte auch der automatische Import.

Google scheint in der iCal Datei bei 76 Zeichen umzubrechen. Ob das jetzt standardkonform o.ä. ist weiß ich nicht, aber es gibt sicher noch mehr Kalender, die beim Export so formatiert sind, da dass Kommentarfeld bei Google großzügig dimensioniert ist. Mehrzeilige SUMMARY: Felder machen aber z.B. keine Probleme.

Bei Bedarf kann ich gerne die betreffenden Kalender + ical-urls zur Verfügung stellen.

Ansonsten weiterhin eine unverzichtbare extension =)

Contao: 3.2.18
calendar_ical: 3.1.0 build 7
ical_creator: 1.0.0 build 15

**Comment by Acta2000** [comment]
Bei mir führte ORGANIZER;CN="" zum gleichen Problem. Der Import brach mit max-execution time ab!

**Comment by hschottm** [comment]
Also zu ORGANIZER;CN="" kann ich nix sagen. Wenn das so in der Datei steht, ist das ja falsch, da keine " verwendet werden dürfen.
Der Abbruch mit dem mehrzeiligen Feld ist behoben durch Verwendung des aktualisierten ical_creator plugins auf Version 1.0.1
